version: '3'

services:
  database:
    image: 'mariadb:latest'
    container_name: kdnummer_db
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql

  webserver:
    build: .
    container_name: kdnummer_webserver
    ports: 
        - "80:80"
    volumes:
        - ./src:/var/www/html
    links:
        - database